@startuml BBドメインモデル図
skinparam componentStyle rectangle
 
 
[会員] o-- [会員ID]
[会員] o-- [氏名]
[会員] o-- [メールアドレス]
[会員] o-- [パスワード]
[会員] o-- [注文詳細]
[会員] o-- [カート]
 
 
[メールアドレス] <|-- [kk10172230@docomo.ne.jp]
 
[注文詳細] o-- [商品]
[注文詳細] o-- [注文]
[注文詳細] o-- [購入数]
[注文詳細] o-- [価格]
 
[カート] o-- [カートID]
[カート] o-- [作成日]
 
[商品] o-- [商品ID]
[商品] o-- [商品名]
[商品] o-- [商品価格]
[商品] o-- [在庫数]
[商品] o-- [商品詳細]
 
[商品詳細] o-- [生産者]
[商品詳細] o-- [生産地]
 
[出荷状況] o-- [発送済み]
[出荷状況] o-- [発送キャンセル]
[出荷状況] o-- [荷物不明]
[出荷状況] o-- [発送前]
 
[決済ログ] o-- [決済金額]
[決済ログ] o-- [決済ID]
[決済ログ] o-- [決済日時]
[決済ログ] o-- [注文ID]
 
[注文] o-- [注文ID]
[注文] o-- [注文日]
[注文] o-- [合計金額]
[注文] o-- [出荷状況]
 
[レビュー] o-- [レビューID]
[レビュー] o-- [内容]
[レビュー] o-- [投稿日]
[レビュー] o-- [投稿]
[レビュー] o-- [表示]
 
[返品] o-- [商品名]
[返品] o-- [商品ID]
[返品] o-- [商品価格]
[返品] o-- [注文詳細]
 
[注文] -- [商品]
[商品] o-- [レビュー]
 
 
@enduml