@startuml 大原情報科学大学・図書館システムドメインモデル図
skinparam componentStyle rectangle

' 中心エンティティ
[図書館システム] o-- [資料タイトル]
[図書館システム] o-- [所蔵資料]
[図書館システム] o-- [会員]
[図書館システム] o-- [貸出]
[図書館システム] o-- [予約]
[図書館システム] o-- [通知]

' 資料タイトルの属性
[資料タイトル] o-- [書名]
[資料タイトル] o-- [著者]
[資料タイトル] o-- [出版社]
[資料タイトル] o-- [資料種別]

' 所蔵資料の属性
[所蔵資料] o-- [管理番号]
[所蔵資料] o-- [状態_所蔵]

' 会員の属性
[会員] o-- [会員番号]
[会員] o-- [氏名]
[会員] o-- [メールアドレス]
[会員] o-- [会員区分]

' 会員の継承
[会員] <|-- [学生]
[会員] <|-- [教職員]

' 貸出の属性
[貸出] o-- [貸出日]
[貸出] o-- [返却期限]
[貸出] o-- [返却日]
[貸出] o-- [状態_貸出]

' 予約の属性
[予約] o-- [予約日]
[予約] o-- [予約者]
[予約] o-- [状態_予約]

' 通知の属性
[通知] o-- [通知日]
[通知] o-- [手段]
[通知] o-- [内容]

@enduml